version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Instala dependencias
          command: npm install
      - run:
          name: Construye la aplicación
          command: npm run build
      - add_ssh_keys:
          fingerprints:
            - ${SSH_KEY} # Opcional, encuentra la huella en CircleCI
      - run:
          name: Despliega en EC2
          command: |
            ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} \<< EOF
            cd /home/ubuntu/frontend/circleejemplo_front
            git pull origin main
            npm install
            npm run build
            EOF

workflows:
  version: 2
  deploy_on_push:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
