version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:23.3.0
    steps:
      - checkout
      - run:
          name: Version de node
          command: npm -v
      - run:
          name: Instala dependencias
          command: npm install
      - run:
          name: Construye la aplicación
          command: npm run build
      - add_ssh_keys:
          fingerprints:
            - ${SSH_KEY} # Opcional, encuentra la huella en CircleCI
      - run:
          name: Despliega en EC2
          command: |
            ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} \<< EOF
            npm -v
            cd /home/ubuntu/frontend/circleejemplo_front
            git pull origin main
            npm run build
            sudo cp -r dist/* /var/www/test1
            sudo chown www-data:www-data /var/www/test1
            EOF

workflows:
  version: 2
  deploy_on_push:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
